### ISSUE TITLE
JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by PlanBit** [LN-Zap/zap-desktop#246] opened 2018-01-28 12:39 UTC
JavaScript error launching Zap.
Can't open it anymore.

![prtscr](https://user-images.githubusercontent.com/35891662/35482099-5ebcfb84-0430-11e8-845d-d30affe4d6d3.JPG)

**Comment by PlanBit** [comment] 2018-01-28 12:45
Restarted the PC and everything was fine.

**Comment by mrfelton** [comment] 2018-07-11 22:48
This issue is from a pretty old version of the wallet. @PlanBit can you confirm if this is still in issue in the latest code in master branch? Thanks.

**Comment by mrfelton** [comment] 2018-07-11 23:01
I'm closing this issue as a duplicate of https://github.com/LN-Zap/zap-desktop/issues/234

**Closed by mrfelton** 2018-07-11 23:01 UTC
Labels: duplicate
