### ISSUE TITLE
Error on startup "JavaScript error occurred in the main process"

### ISSUE THREAD

**Issue by coolpick** [LN-Zap/zap-desktop#254] opened 2018-01-28 18:11 UTC
Started up the first time without a problem.  I attempted to let Chrome open a lightning address with Zap, but it opened a second instance.  This error showed.  When I re-launched both to re-test, I started getting this error.  After dismissing error, lightning fails to connect to anything, is indefinitely loading.

Before the error:
- Attempted to open lightning url via chrome
- Second instance was opened
- Manually created peer, double clicked and two were showing as pending

Issue could be related to any of the above, or completely random.  Have not been able to find a log file anywhere.

About 10 minutes later, the error has gone away.  I'm leaning toward it being related to the port or a windows process.  A task hanging.

![zap](https://user-images.githubusercontent.com/1341176/35485353-673db356-042c-11e8-835b-1848243b3ac7.png)

**Comment by Ceratodontiformes** [comment] 2018-01-31 21:21
Same error here. Also Win (7).
- Trying to set up channel.
- Zap becomes "slow"
- Close Zap
- Open Zap -> Error
- open/close/open/close -> always error
- reboot -> still error

- after several minutes -> reopened -> error gone.

// thx for the awsome project

**Comment by cavapoo2** [comment] 2018-02-13 17:19
Similar error: 
```
Uncaught Exception:
Error: Connect Failed
    at ClientReadableStream._emitStatusIfDone (/home/febe/lightning/zap/zap-desktop/app/node_modules/grpc/src/client.js:255:19)
    at ClientReadableStream._readsDone (/home/febe/lightning/zap/zap-desktop/app/node_modules/grpc/src/client.js:221:8)
    at readCallback (/home/febe/lightning/zap/zap-desktop/app/node_modules/grpc/src/client.js:283:12)
```

I running simnet (btcd) and 2 lnd nodes (lnd version 0.3.0-alpha). I think i need to learn lightning code in more detail before playing around with this.

**Comment by mrfelton** [comment] 2018-07-11 23:03
Closing as a duplicate of https://github.com/LN-Zap/zap-desktop/issues/234

**Closed by mrfelton** 2018-07-11 23:03 UTC
Labels: bug, duplicate
