### ISSUE TITLE
Investigate backup error

### ISSUE THREAD

**Issue by korhaliv** [LN-Zap/zap-desktop#2131] opened 2019-04-29 12:14 UTC
## Description
The following error has appeared after the creation of a brand new mainnet local wallet. 
Looks like this has something to do with file locks and/or concurrent modification request
```
[ERR]  2019-04-29 14:57:06.113 [ERR] CHBU: Unable to refresh backup file: 
unable to update multi backup: 
rename \AppData\Roaming\Electron\lnd\bitcoin\mainnet\wallet-128\data\chain\bitcoin\mainnet\temp-dont-use.backup \AppData\Roaming\Electron\lnd\bitcoin\mainnet\wallet-128\data\chain\bitcoin\mainnet\channel.backup: 
The process cannot access the file because it is being used by another process. +8ms
```

- Zap version: `next`
- Operating System and version: win10 x64

**Comment by mrfelton** [comment] 2019-06-18 21:41
This issue occurred with an earlier version of lnd and hasn't been seen again since it was logged. Closing as not reproducible.

**Closed by mrfelton** 2019-06-18 21:41 UTC
Labels: type: bug 🐛
