### ISSUE TITLE
Display status of force closed channels

### ISSUE THREAD

**Issue by bg002h** [LN-Zap/zap-desktop#1176] opened 2018-12-24 00:22 UTC
## Detailed Description

Forced closed channels are currently listed as 0 amount transactions. The command lncli pendingchannels can show what LND believes the final amount will be at time of time lock maturity, but Zap doesn't use this info in it's visual representation of the transaction.

## Context

Whenever force closing a channel, for example when a node is no longer reachable, the funds disappear in the Zap UI. The UI doesn't give any hint as to where the funds are, when they will return, and how much of the channel will be coming back to the user.

## Possible Implementation

Force close channels could get data on what LND believes the channel balance will be at maturity and when that occurs.  An icon of a clock to indicate that waiting must occur for the tx to mature or simply listing the tx in the pending transaction section could let the user know what to expect.

## Your Environment

- Zap Desktop version: 0.3.1
- Operating System and version: Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

**Comment by Jonbros01** [comment] 2019-01-02 16:30
Few days ago I had a channel with Coincards that went offline... the next day it was still offline so I decided to close the channel.  Since then their 110 block confirmation and the channel is still labeled as closing...  why it is taking that long?  anything I should do to get back the funds of the channel??

**Comment by JimmyMow** [comment] 2019-01-04 14:46
@Jonbros01 @wuestenigel this is not a bug, it is the intended functionality. When you initiate a force close your txs are time locked, as this gives the other channel party time to dispute and handle any cheating. It is a key concept in the design of the Lightning Network.

The scope of this issue seems to be UI/UX related, but the functionality is working as intended.

**Comment by Jonbros01** [comment] 2019-01-04 14:52
Their should be a timer in ZAP that countdown the duration of the closing, this would make it more comprehensive.

**Comment by JimmyMow** [comment] 2019-01-04 14:55
Sure. We are working on a total re-design of all our channel related UIs, this issue included

**Comment by Jonbros01** [comment] 2019-01-04 15:52
I lost track of time but I would say 2-4 days

**Comment by mrfelton** [comment] 2019-03-04 20:23
Closed via https://github.com/LN-Zap/zap-desktop/pull/1680

**Closed by mrfelton** 2019-03-04 20:23 UTC
Labels: scope: channels, type: feature
