### ISSUE TITLE
Waiting for peers, synching again

### ISSUE THREAD

**Issue by wdey** [LN-Zap/zap-desktop#2180] opened 2019-05-09 15:23 UTC
Sorry, I'm running the newest version 0.4.1 and have the same problem (Windows 10). like in #660
Reinstall, downgrade to 0.4.0 didn't work
Could it be related to the fact, that my IP address changed ? 
I deinstalled, deleted any files remaining after the delete.
Reinstall and recover by means of the 24 words
Now, I cannot even see my on chain resources ! 
Something is wrong in the nursery ! LMA !

**Comment by mrfelton** [comment] 2019-05-09 19:11
Our btcd nodes were down for a bit. Should be back up up.

**Comment by wdey** [comment] 2019-05-09 20:23
ZAP is up again, but the recovery (24 word) didn't work. I have now 0 sat.
Strange enough I see 2 BTC on chain transaction, one sent (200'000 sat), one received (200'000 sat) both of today, and did none of them myself. I loaded my account about 2 weeks ago with 200'000.
The tx id's are 
Sent:
d8b91091823cec1d051d95ac4158ac68fe17ea7f6f200128f46d6bea2b97a530
Date of confirmation April 09, 2019 5:30 PM with 4404 confirmations !!!!!!!!!!!!!
Received:
75ac19514d6a3aaacfe50f0933d83b183961757bc66aba88e03361cfb2554d9d
Date of confirmation April 09, 2019 2:36 PM with 4422 confirmations !!!!!!!!!!

**Comment by mrfelton** [comment] 2019-05-09 20:29
Did you have autopilot enabled (which would automatically open channels for you - thus creating on-chain transactions)?

If you had channels open and funds locked in channels, then doing a restore from seed would not recover those funds (the current restore functionality only recovers on-chain funds)

**Comment by wdey** [comment] 2019-05-09 20:36
By default autopilot is disabled ? correct ? and enabling must be done when inital setup !
In that case, no! 
I had one channel open with 20'000 sat, that's it.
Understand that channel funds are lost, but recovery not even works for on chain funds.
Look what this tx are displaying, I am sorry, but the information is totally wrong

**Comment by mrfelton** [comment] 2019-05-09 20:47
It might be worth trying to recover using the ‘next’ branch (code for upcoming 5.x release). The recovery process has had some updates, including an increased recovery window from 250 to 2500, and better monitoring through the recovery process.

One question - when you did the restore from seed, did you let it sync all the way through from start to finish without stopping in the middle (restarting the app or logging out of and then into the wallet again)? Your original post was about having some sync issues, so I’m wondering if you stopped and restarted the sync mid way through (which could affect the recovery)

**Comment by wdey** [comment] 2019-05-09 20:58
The story started, when I had to restart my Windows 10, and ZAP was dead, no more synching.
Then I tried misc. things, like reinstall, delete all and reinstall, downgrade version.
Finally I deleted tabula rasa everything, and started with the recovery
Nothing happened ! I left my desk, totally frustrated !
When I came back a few hours later, the sync had started but hung at exactly 50% for probably 2 hours. 
The I read your comment that a server was down.
I shutdown ZAP and did a restart, which then finished in about 5 minutes

**Comment by mrfelton** [comment] 2019-05-09 21:02
Ok, in that case I don’t think it would have actually done a full restore. Please delete the wallet and try to restore the seed again. Leave it open until it has fully synced and recovered.

Note: in 0.4.1 it can look like it has hung at 99% at the end of the sync process, but in actual fact it is doing the recovery part (in 5.x we show another progress bar whilst the recover is taking place so that it’s more clear that it’s still doing something)

**Comment by mrfelton** [comment] 2019-05-09 21:09
See the following for reference:

https://github.com/LN-Zap/zap-desktop/issues/2080

https://github.com/LN-Zap/zap-desktop/pull/2133

(These is the known issue with wallet recovery in 4.x that is improved in 5.x)

**Comment by wdey** [comment] 2019-05-09 21:19
Thanks for your great support
I have the following questions
- Could you not signal a useful error message, when your server is down, causing trouble
- Is this a custodial server, and if yes for what (or are you open a channel to your lnd node ?)
- how can I get back to this initial recovery menu! deinstall/reinstall doesn't do it ?

**Comment by mrfelton** [comment] 2019-05-09 21:26
> Could you not signal a useful error message, when your server is down, causing trouble

We could. Could you open a new feature request for that please? 

> Is this a custodial server, and if yes for what (or are you open a channel to your lnd node ?)

No. It is running an lnd neutrino light client on your machine. Your keys, your money, your control. It connects to our btcd nodes in order to fetch the blockchain data that’s all. 

> how can I get back to this initial recovery menu! deinstall/reinstall doesn't do it ?

Log out of the wallet (open the drop down menu at the top right of the wallet and click “logout”, where it says your wallet name with a little green dot next to it). That will take you to the launchpad area where you can manage all of your nodes.

**Comment by wdey** [comment] 2019-05-10 10:25
I did it, without success ! starting from scratch again.

**Comment by mrfelton** [comment] 2019-05-11 19:37
I'm going to close this issue since the cause of the original issue was that our btcd nodes were down and these are now back up again.

The other issues mentioned in this thread are being handled through various other issues, including:

https://github.com/LN-Zap/zap-desktop/issues/2187
https://github.com/LN-Zap/zap-desktop/issues/2184
https://github.com/LN-Zap/zap-desktop/issues/2185

**Closed by mrfelton** 2019-05-11 19:37 UTC
