### ISSUE TITLE
[mac] Error: mainWindow is not defined

### ISSUE THREAD

**Issue by dasilvarosa** [LN-Zap/zap-desktop#249] opened 2018-01-28 12:52 UTC
Zap is synchronized and no channel is yet open (1 pending). 

When clicking on a payment request URI I get the following error: 

> Uncaught Exception:
> Error: "mainWindow" is not defined
>     at App.d.app.on (/private/var/folders/b8/c2dz20d92t796jkykxvfh52c0000gn/T/AppTranslocation/DD711D27-EE99-4493-981D-C652673A95A9/d/Zap.app/Contents/Resources/app.asar/webpack:/app/main.dev.js:286:31)
>     at emitTwo (events.js:106:13)
>     at App.emit (events.js:191:7)

Then a second Zap window opens.

![uri-error](https://user-images.githubusercontent.com/712580/35482244-71b6828a-0432-11e8-820c-83119514f581.gif)

**Comment by dasilvarosa** [comment] 2018-01-28 13:11
To be precise: the channel is now opened but the behaviour remains the same.

**Comment by slack333** [comment] 2018-01-28 14:41
![captura de pantalla 2018-01-28 a la s 11 34 39](https://user-images.githubusercontent.com/25033440/35483357-a3be0fae-041f-11e8-8b84-092c7fd517ac.png)

I have the same issue when I open the app. Yesterday worked so well and today I close it and open again with this problem.

**Comment by mrfelton** [comment] 2018-07-13 06:42
I have been unable to reproduce this issue. Please can you verify if this is an issue with the latest code in the master branch and if so provide steps for how to reproduce? Thanks.

**Comment by mrfelton** [comment] 2018-07-23 12:43
Closing due to inactivity. Looks like this relates to an older version of the app and grpc client. @dasilvarosa please feel free to reopen if you can reproduce this issue with the latest codebase.

**Closed by mrfelton** 2018-07-23 12:43 UTC
Labels: bug
