### ISSUE TITLE
Connecting to a node didn't ask how much and sent all my coin

### ISSUE THREAD

**Issue by DataCourier** [LN-Zap/zap-desktop#282] opened 2018-02-04 14:46 UTC
I clicked on `Connect` in this dialog and without asking, I get all my coins allocated into that channel.

![screenshot 2018-02-04 15 40 33](https://user-images.githubusercontent.com/35670446/35778709-51c1d110-09c2-11e8-8376-46a3f7eb5bfb.png)

Also, the loading animation after I clicked connect (where now it says pending) wold make the scrollbars flicker a lot (there shouldn't be horizontal scrollbar in the first place though).

**Comment by DataCourier** [comment] 2018-02-04 14:56
Correction, all was not sent, but it looked that way because the wallet said I have 0 coin in channels and 0 overall.

**Comment by JimmyMow** [comment] 2018-02-06 16:42
Sounds like you had 1 UTXO that the wallet used to open the channel. Not a bug. Wallet balance was 0 because Zap uses a light client. Closing

**Closed by JimmyMow** 2018-02-06 16:42 UTC
