### ISSUE TITLE
stuck on loading screen after  update 

### ISSUE THREAD

**Issue by ac-com-au** [LN-Zap/zap-desktop#1375] opened 2019-01-17 08:43 UTC
## Your Environment
remote LND node on LAN network .Connection was working perfect before update.

- Zap Desktop version:ZapDesktop-win32-v0.3.3-beta.exe
- Operating System and version: win10 Pro

**Comment by mrfelton** [comment] 2019-01-17 12:06
Closing as a duplicate of https://github.com/LN-Zap/zap-desktop/issues/1320 (confirmed in slack)

**Closed by mrfelton** 2019-01-17 12:06 UTC
Labels: duplicate
