### ISSUE TITLE
[windows UI] channel status selector is getting cut off

### ISSUE THREAD

**Issue by justsomedude4242** [LN-Zap/zap-desktop#316] opened 2018-02-22 14:34 UTC
windows 10 64 bit

the box for displaying / choosing  "All / online / pending / closing"  is to small and gets cut off.

![online](https://user-images.githubusercontent.com/35006790/36543932-7740532c-17e5-11e8-8fa7-9ea17590d04e.png)

![pending](https://user-images.githubusercontent.com/35006790/36543933-775ade2c-17e5-11e8-8f8b-06e3e88a908d.png)

![closing](https://user-images.githubusercontent.com/35006790/36543931-7723d0e4-17e5-11e8-9525-6a91d21f8040.png)

**Comment by odb366** [comment] 2018-03-21 19:42
@justsomedude4242 Could you update to the last version and check if the problem is solved

**Comment by JimmyMow** [comment] 2018-05-04 00:08
Should be resolved in master. Closing this

**Closed by JimmyMow** 2018-05-04 00:08 UTC
Labels: UX/UI
