### ISSUE TITLE
Unhandled React exception

### ISSUE THREAD

**Issue by nikodean1** [LN-Zap/zap-desktop#3509] opened 2020-05-11 16:47 UTC
Detailed Description
-------
``TypeError: Cannot read property 'color' of undefined
    at file:///tmp/.mount_Zap-limbnKzj/resources/app.asar/dist/renderer.js:318:961758
    at rx (file:///tmp/.mount_Zap-limbnKzj/resources/app.asar/dist/renderer.js:318:961872)
    at fa (file:///tmp/.mount_Zap-limbnKzj/resources/app.asar/dist/renderer.js:42:59532)
    at xs (file:///tmp/.mount_Zap-limbnKzj/resources/app.asar/dist/renderer.js:42:104763)
    at Ic (file:///tmp/.mount_Zap-limbnKzj/resources/app.asar/dist/renderer.js:42:90342)
    at Pc (file:///tmp/.mount_Zap-limbnKzj/resources/app.asar/dist/renderer.js:42:90267)
    at wc (file:///tmp/.mount_Zap-limbnKzj/resources/app.asar/dist/renderer.js:42:87607)
    at file:///tmp/.mount_Zap-limbnKzj/resources/app.asar/dist/renderer.js:42:45937
    at t.unstable_runWithPriority (file:///tmp/.mount_Zap-limbnKzj/resources/app.asar/dist/renderer.js:50:3465)
    at Kr (file:///tmp/.mount_Zap-limbnKzj/resources/app.asar/dist/renderer.js:42:45646)``
        
Your Environment
----
- Zap version: Zap 0.6.2-beta

**Comment by bolatovumar** [comment] 2020-05-12 03:26
This is a duplicate of this: https://github.com/LN-Zap/zap-desktop/issues/3277. This bug has been fixed.

**Closed** 2020-05-12 07:18 UTC
