### ISSUE TITLE
All activities should include all activities

### ISSUE THREAD

**Issue by marsrobertson** [LN-Zap/zap-desktop#2278] opened 2019-05-26 12:10 UTC
`0.4.1-beta` on Mac

![zap all  2019-05-26 11_32_29](https://user-images.githubusercontent.com/44369284/58380515-06659800-7faa-11e9-967a-b9fab9fd6827.gif)

**Comment by marsrobertson** [comment] 2019-05-26 19:11
While we are at it, probably a better wording:

* pending as in unconfirmed in the mempool
* requested as in I've created an invoice

![image](https://user-images.githubusercontent.com/44369284/58386062-59633d80-7ff2-11e9-99c7-9c8fcaf5c021.png)

**Comment by mrfelton** [comment] 2019-05-27 04:29
> All activities should include all activities

So, this is also by design though clearly needs to be better worded. The `all` category only shows actual transactions that you have initiated and excludes internal transactions such as channel opening or closing transactions. Clearly the label `all` is a little misleading.

The reason for not including the internal transactions on the default (all) transaction list is that often time those transactions are not something that a user would want to concern themselves with. For example, if you have autopilot turned on the system will automatically open and close channels for you but the transactions related to those system actions are not user initiated transactions and would be confusing to users to see transactions appearing in their main transaction list that they didn't initiate.

The label `All` obviously is misleading. Open to suggestions for better labeling...

> While we are at it, probably a better wording:
> 
> - pending as in unconfirmed in the mempool
> - requested as in I've created an invoice

I'm not quite sure I understand your suggestion. Can you elaborate please?

**Comment by marsrobertson** [comment] 2019-05-27 07:49
> While we are at it, probably a better wording:
> 
> * pending as in unconfirmed in the mempool
> * requested as in I've created an invoice

I have requested payment. 

Requested payment should be in category "requested"

![image](https://user-images.githubusercontent.com/44369284/58404034-15a51e00-805c-11e9-88fe-0cd3024b46ee.png)

The pending category is typically reserved for transactions that are pending, transactions that are unconfirmed in the mempool.

-----

Another way of looking at it: you can have 1000 requested transactions. You are likely to have 1-2 pending in the mempool.

**Comment by marsrobertson** [comment] 2019-05-27 08:45
> excludes internal transactions such as channel opening or closing transactions

> system will automatically open and close channels

My (fairly limited) understanding is that opening / closing channel requires an on-chain transaction and an associated cost.

As a user I'm interested in knowing when this is happening.

Given the target audience, your users are interested in seeing that?

**Comment by mrfelton** [comment] 2019-05-27 08:50
In previous iterations of the app we included all transactions on the default `all` list and it was really confusing because you see all these transactions that you didn't initiate (channel openings and closing etc). Users found this confusing, so we recategorised these internal/automated transactions and hid them away in the `internal` tab so that users can focus on their actual transaction history (the times where they specifically sent or received money to some service etc).

You can still see them in the internal tab, they are just out of the way by default so that your general day to day spending from the wallet is not cluttered with internal stuff that is not relevant in the context of day to day usage of the wallet.

**Comment by marsrobertson** [comment] 2019-05-27 09:15
Understood.

I'm not day-to-day user.

I'm a developer trying to figure things out and I was really confused then things happen behind my back.

See #2280 

I guess it could be related to autopilot.

Once I'll learn more I'll be able to contribute in a more meaningful way.

**Comment by bolatovumar** [comment] 2019-08-10 14:19
I was also confused by this expecting "All" to show all transactions including channel funding and closing and whatnot.

I suspect this may differ from user to user. Non-technical users probably don't wanna see channel funding/closing transactions under "All" while technical users who are aware how LN works under the hood would probably expect to see everything under "All".

I'm not sure if there is anything that needs to be done here. Maybe we wait and see if more people are confused by this.

**Comment by marsrobertson** [comment] 2019-08-11 04:15
`internal` is `internal`
`ALL` is `ALL`

You can call it `under the hood` or anything but `ALL` should be `ALL`

I was really confused. @bolatovumar  person is confused too (thanks for posting).

Simple. No need to overcomplicate.

**Comment by bolatovumar** [comment] 2019-08-11 08:41
@marsrobertson I think the issue here is that non-technical users may not think of opening channels or closing channels as "transactions" so they may get confused when seeing these transactions under `ALL`. This is especially true if using autopilot.

**Comment by mrfelton** [comment] 2019-08-11 08:44
We just need to come up with a better name for it. What we currently call "all" is categorically not all, deliberately. We don't want the default view to show everything.

Maybe we just rename the current "all" to "default" or something like that and then add a new "all" section which actually shows all items.

**Comment by bolatovumar** [comment] 2019-08-11 08:51
@mrfelton maybe we also add an on-hover tooltip (by simply adding the title attribute to filter titles) which would explain what "default" or "all" means. People might be confused what "default" is and why it's the way it is.

**Comment by marsrobertson** [comment] 2019-08-11 09:01
@bolatovumar 

> I think the issue here is that non-technical users may not think of opening channels or closing channels as "transactions" so they may get confused when seeing these transactions under ALL. This is especially true if using autopilot.

**may get confused**

I admit I was confused AF the other way round: https://github.com/LN-Zap/zap-desktop/issues/2280#issuecomment-496934503

**Comment by bolatovumar** [comment] 2019-08-11 09:02
@marsrobertson see @mrfelton's comment above:

https://github.com/LN-Zap/zap-desktop/issues/2278#issuecomment-496134654

I believe he is speaking from experience.

**Comment by mrfelton** [comment] 2019-08-11 09:36
> maybe we also add an on-hover tooltip

@bolatovumar this might not be a bad idea actually. All of those filter options could probably benefit from a brief description.

I'm not sure that we have any examples of using hover hints in conjunction with items in a dropdown, but I'd be interested to see how it feels.

**Comment by bolatovumar** [comment] 2019-08-11 10:17
@mrfelton Here are some screenshots using the `data-hint` attribute Zap uses:

![Screen Shot 2019-08-11 at 1 11 44 PM](https://user-images.githubusercontent.com/1934678/62832613-b659b180-bc39-11e9-9365-a5eca720f77b.png)
![Screen Shot 2019-08-11 at 1 11 52 PM](https://user-images.githubusercontent.com/1934678/62832618-c7a2be00-bc39-11e9-9099-e5100792b99d.png)

As you can see it doesn't quite work. At least not in the way the `data-hint` attribute is implemented currently.

Here are some screenshots with just using the standard `title` attribute (which triggers a tooltip after you hover over an item for a second or so):

![Screen Shot 2019-08-11 at 1 10 26 PM](https://user-images.githubusercontent.com/1934678/62832629-f7ea5c80-bc39-11e9-94ac-9670a4a6568b.png)
![Screen Shot 2019-08-11 at 1 08 47 PM](https://user-images.githubusercontent.com/1934678/62832633-105a7700-bc3a-11e9-8335-73dec288bd5c.png)

**Comment by mrfelton** [comment] 2019-08-11 10:39
hmm, so of all of these I think the only one that really works is the first one - showing a styled hover hint over the control itself rather than the individual items in the dropdown. This follows a similar pattern that we use elsewhere, eg:

![image](https://user-images.githubusercontent.com/200251/62832800-32e59380-bc2c-11e9-8b55-2dfe44bfda26.png)

![image](https://user-images.githubusercontent.com/200251/62832802-3c6efb80-bc2c-11e9-920c-73982569a8eb.png)

Although if it were following that pattern it should show showing a hint that describes what the control does (eg "Filter the activity list") rather than describing what the currently active filter does.

Also, there obviously looks to be some kind of display glitch shown in your screenshot since the text should be broken over multiple lines rather than breaking out of the box.

I don't think we should use the system tooltip since it doesn't fir in with our overall designs.

**Comment by mrfelton** [comment] 2019-11-06 17:34
Closed via https://github.com/LN-Zap/zap-desktop/pull/3101

**Closed by mrfelton** 2019-11-06 17:34 UTC
Labels: scope: ui/ux
