### ISSUE TITLE
Failed to connect to 127.0.0.1:18333

### ISSUE THREAD

**Issue by fredbeltrao** [LN-Zap/zap-desktop#307] opened 2018-02-16 12:44 UTC
Ubuntu 16.04

Tryning to run Zap for the first time.

- The frontend remains on 0%. 
- 8 lnd processes running without any cpu consume
- .lnd/logs/testnet3/bitcoin/lnd.log displays these messages:

```
2018-02-16 09:30:45.123 [DBG] BTCN: Received addr (1000 addr) from 207.154.242.226:18333 (outbound)
2018-02-16 09:30:45.728 [INF] LNWL: The wallet has been unlocked without a time limit
2018-02-16 09:30:45.729 [INF] LTND: LightningWallet opened
2018-02-16 09:30:45.775 [INF] LNWL: Started rescan from block 000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943 (height 0) for 1 address
2018-02-16 09:30:45.775 [INF] LNWL: Catching up block hashes to height 0, this might take a while
2018-02-16 09:30:45.833 [INF] LNWL: Done catching up block hashes
2018-02-16 09:30:45.834 [INF] LNWL: Finished rescan for 1 address (synced to block 000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943, height 0)
2018-02-16 09:30:45.846 [INF] RPCS: RPC server listening on 127.0.0.1:10009
2018-02-16 09:30:45.846 [INF] LTND: Waiting for chain backend to finish sync, start_height=0
2018-02-16 09:30:45.846 [INF] RPCS: gRPC proxy started at 127.0.0.1:8080
2018-02-16 09:30:47.014 [INF] CMGR: 50 addresses found from DNS seed testnet-seed.bitcoin.schildbach.de
2018-02-16 09:30:47.047 [DBG] CRTR: New graph topology client subscription, client 1
2018-02-16 09:30:49.041 [DBG] CMGR: Attempting to connect to 127.0.0.1:18333 (reqid 2)
2018-02-16 09:30:49.041 [DBG] CMGR: Failed to connect to 127.0.0.1:18333 (reqid 2): dial tcp 127.0.0.1:18333: getsockopt: connection refused
2018-02-16 09:30:49.041 [DBG] CMGR: Retrying connection to 127.0.0.1:18333 (reqid 2) in 10s

```

**Comment by JimmyMow** [comment] 2018-02-19 03:31
`Failed to connect to 127.0.0.1:18333` is not a bug, it is just checking for a full node that supports neutrino on your local machine.

`Received addr (1000 addr) from 207.154.242.226:18333` means you established a connection with `207.154.242.226`, which is my full node. I know recently there were some funky issues on testnet, I reset my node and things should be resolved. Are you still facing issues? Going to close this for now

**Closed by JimmyMow** 2018-02-19 03:31 UTC
