### ISSUE TITLE
Problems syncing to the blockchain (No connection could be made because the target machine actively refused it)

### ISSUE THREAD

**Issue by simonsolberg** [LN-Zap/zap-desktop#618] opened 2018-07-26 18:39 UTC
Running Zap.Setup.0.2.0-beta.exe. 

Screenshot: 
![image](https://user-images.githubusercontent.com/31542525/43281297-9c410e1c-9113-11e8-900b-f73cc68b9a36.png)

lnd.log: these messages keep repeating
`2018-07-26 20:35:17.021 [DBG] CMGR: Retrying connection to 206.189.72.180:18333 (reqid 1) in 1m5s
2018-07-26 20:36:14.692 [DBG] CMGR: Attempting to connect to 127.0.0.1:18333 (reqid 2)
2018-07-26 20:36:15.701 [DBG] CMGR: Failed to connect to 127.0.0.1:18333 (reqid 2): dial tcp 127.0.0.1:18333: connectex: No connection could be made because the target machine actively refused it.
2018-07-26 20:36:15.701 [DBG] CMGR: Retrying connection to 127.0.0.1:18333 (reqid 2) in 1m10s
2018-07-26 20:36:22.021 [DBG] CMGR: Attempting to connect to 206.189.72.180:18333 (reqid 1)
2018-07-26 20:36:23.580 [DBG] CMGR: Failed to connect to 206.189.72.180:18333 (reqid 1): dial tcp 206.189.72.180:18333: connectex: No connection could be made because the target machine actively refused it.
2018-07-26 20:36:23.580 [DBG] CMGR: Retrying connection to 206.189.72.180:18333 (reqid 1) in 1m10s
2018-07-26 20:37:25.703 [DBG] CMGR: Attempting to connect to 127.0.0.1:18333 (reqid 2)
2018-07-26 20:37:26.710 [DBG] CMGR: Failed to connect to 127.0.0.1:18333 (reqid 2): dial tcp 127.0.0.1:18333: connectex: No connection could be made because the target machine actively refused it.
2018-07-26 20:37:26.710 [DBG] CMGR: Retrying connection to 127.0.0.1:18333 (reqid 2) in 1m15s
2018-07-26 20:37:33.587 [DBG] CMGR: Attempting to connect to 206.189.72.180:18333 (reqid 1)
2018-07-26 20:37:35.160 [DBG] CMGR: Failed to connect to 206.189.72.180:18333 (reqid 1): dial tcp 206.189.72.180:18333: connectex: No connection could be made because the target machine actively refused it.
2018-07-26 20:37:35.160 [DBG] CMGR: Retrying connection to 206.189.72.180:18333 (reqid 1) in 1m15s
`

**Comment by mntetai** [comment] 2018-07-26 21:38
same here ... 206.189.72.180:18333 is down ...

**Comment by JimmyMow** [comment] 2018-07-28 01:43
Can you all try restarting Zap and see if you still face this issue? Our BTCD was having issues and I've applied a patch to resolve it

**Comment by skcheffy** [comment] 2018-07-28 01:46
Ok, I was able to get back in.  Going to test some transactions out and will let you know.

**Comment by skcheffy** [comment] 2018-07-28 01:49
Please see the below error message i got.

![screen shot 2018-07-27 at 9 48 22 pm](https://user-images.githubusercontent.com/31999006/43351865-e02c707a-91e6-11e8-858c-eb0d6b6768d5.png)

**Comment by JimmyMow** [comment] 2018-07-28 01:53
Ok interesting. What caused this error?

**Comment by skcheffy** [comment] 2018-07-28 01:56
I signed in, got past the initial first error where it let me to the dashboard.  I was just waiting for the channels to show green so I could attempt a transaction and the error just popped up.  Once I exited the Error it shut Zap down.

Sorry I am not too technical so not sure how to run an error log or anything.  If there is something you want me to do to give you more info just let me know.

**Comment by mrfelton** [comment] 2018-07-28 06:39
The original problem described in this issue id due to BTCd refusing connections which was because our BTCd node was having issues at the time. Those issues should hopefully be resolved now as per @jackmallers 's previous comments.

The second is I believe to be a duplicate of https://github.com/LN-Zap/zap-desktop/issues/601 for which I'm already working on a fix.

**Closed by mrfelton** 2018-07-28 06:39 UTC
Labels: bug
