### ISSUE TITLE
JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by mdotbit** [LN-Zap/zap-desktop#1442] opened 2019-01-29 00:43 UTC
I open zap (0.3.3-beta.5477) through Node Launcher version 5.4.0 and get the following "JavaScript error occurred in the main process"

Uncaught Exception:
TypeError: Cannot read property 'sendMessage' of undefined
    at s (/Applications/ZapDesktop.app/Contents/Resources/app.asar/dist/webpack:/app/main.js:129:30)
    at show (/Applications/ZapDesktop.app/Contents/Resources/app.asar/dist/webpack:/app/main.js:49:14)
    at App.platform (/Applications/ZapDesktop.app/Contents/Resources/app.asar/dist/webpack:/app/main.js:304:10)
    at App.emit (events.js:182:13)

Zap then opens and I see my wallet but clicking "Launch Now" is unresponsive and eventually leads to a blank blue screen. 

Running on main net and on a Mac.

**Comment by pedromvpg** [comment] 2019-01-29 02:34
Also happening on my end since I started running the latest version of Node Launcher version 5.4.0.

![screen shot 2019-01-28 at 8 40 07 pm](https://user-images.githubusercontent.com/807505/51880202-62921580-2344-11e9-95b3-ca7ef2802d7c.png)

**Comment by JimmyMow** [comment] 2019-01-29 02:37
What version of LND is the latest version of the Node Launcher using?

**Comment by mdotbit** [comment] 2019-01-29 02:42
LND version v0.5.2-beta-rc3

**Comment by JimmyMow** [comment] 2019-01-29 02:45
Ok yeah makes sense. LND has a breaking API change that isn’t backwards compatible. We have a PR up that should be merged soon that will work with any LND API, and once it’s merged we will release a new version as well, but our last release was built with LND 0.5.1 in mind.

**Comment by mrfelton** [comment] 2019-01-29 07:44
This is a bug in Zap `0.3.3`. IT is fixed in the `master` branch and will be fixed in `0.3.4` when we release that (very soon).

As a work around, please make sure that you open Zap first, before clicking the links from node launcher.

**Comment by otaviobps** [comment] 2019-01-30 13:50
I'm running `v0.5.1-beta-532` since yesterday and got this error as well. Now it doesn't appear anymore, but I'm stuck in the loading page

**Comment by mrfelton** [comment] 2019-01-30 13:55
@otaviobps the issue is that you are using the latest lnd version and we currently only support version `0.5.1-beta` since there are some breaking changes in the most recent lnd version.

We have a patch to support recent versions of lnd here https://github.com/LN-Zap/zap-desktop/pull/1431 which we should be merging soon and will include in our next release (`0.3.4-beta`)

**Comment by otaviobps** [comment] 2019-01-30 13:57
Thanks @mrfelton, gonna wait for the next release

**Comment by mdotbit** [comment] 2019-01-30 18:32
> This is a bug in Zap `0.3.3`. IT is fixed in the `master` branch and will be fixed in `0.3.4` when we release that (very soon).
> 
> As a work around, please make sure that you open Zap first, before clicking the links from node launcher.

When I try the work around I get this error which I assume is related: 

Uncaught Exception:
TypeError: Cannot read property 'show' of undefined
    at App.app (/Applications/ZapDesktop.app/Contents/Resources/app.asar/dist/webpack:/app/main.js:302:1)
    at App.emit (events.js:182:13)

I have an onchain bitcoin balance which I'd like to send elsewhere and after 3-4 tries of opening Zap I finally get to the send screen and as soon as I enter the amount of btc to send, Zap goes blank.

**Comment by mrfelton** [comment] 2019-02-08 19:49
Hi. We have just released Zap Desktop 0.3.4-beta which you can download from here https://github.com/LN-Zap/zap-desktop/releases/tag/v0.3.4-beta.

Please let me know if this is still an issue for you in the latest release. Thanks.

**Comment by mdotbit** [comment] 2019-02-08 20:45
I don't get the Javascript error, Thanks. 

However when I try to send a on-chain payment, after I enter the destination address, I try to type "." to send .01 but then the Zap goes blank.

**Comment by JimmyMow** [comment] 2019-02-09 01:32
@mdotbit oh wow, thanks for reporting that. If you type `0.` (put a 0 before the period), then it will work. We will fix that shortly

**Comment by mrfelton** [comment] 2019-02-10 10:20
I'm going to close this issue as the original javascript issue that was reported is no longer an issue.

@mdotbit The issue with the amount input field will be addressed in https://github.com/LN-Zap/zap-desktop/issues/1547 .

**Closed by mrfelton** 2019-02-10 10:20 UTC
Labels: type: bug
