### ISSUE TITLE
Unhandled React exception after wallet recovery reached 100%

### ISSUE THREAD

**Issue by SamSamskies** [LN-Zap/zap-desktop#3476] opened 2020-04-19 17:28 UTC
Detailed Description
-------
``TypeError: Cannot read property 'color' of undefined
    at file:///Applications/Zap.app/Contents/Resources/app.asar/dist/renderer.js:318:961758
    at rx (file:///Applications/Zap.app/Contents/Resources/app.asar/dist/renderer.js:318:961872)
    at fa (file:///Applications/Zap.app/Contents/Resources/app.asar/dist/renderer.js:42:59532)
    at xs (file:///Applications/Zap.app/Contents/Resources/app.asar/dist/renderer.js:42:104763)
    at Ic (file:///Applications/Zap.app/Contents/Resources/app.asar/dist/renderer.js:42:90342)
    at Pc (file:///Applications/Zap.app/Contents/Resources/app.asar/dist/renderer.js:42:90267)
    at wc (file:///Applications/Zap.app/Contents/Resources/app.asar/dist/renderer.js:42:87607)
    at file:///Applications/Zap.app/Contents/Resources/app.asar/dist/renderer.js:42:45937
    at t.unstable_runWithPriority (file:///Applications/Zap.app/Contents/Resources/app.asar/dist/renderer.js:50:3465)
    at Kr (file:///Applications/Zap.app/Contents/Resources/app.asar/dist/renderer.js:42:45646)``
        
Your Environment
----
- Zap version: Zap 0.6.2-beta

**Comment by mrfelton** [comment] 2020-05-09 12:06
Hi, thanks for reporting this. I believe it's a duplicate of https://github.com/LN-Zap/zap-desktop/issues/3258 and https://github.com/LN-Zap/zap-desktop/issues/3277 and should be fixed in master. Fix will be in the next release.

**Closed by mrfelton** 2020-05-09 12:06 UTC
Labels: type: bug 🐛
