### ISSUE TITLE
ERROR : A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by copyket** [LN-Zap/zap-desktop#235] opened 2018-01-27 17:33 UTC
" ERROR : A JavaScript error occurred in the main process " 

I can't run in win 10.

How can fix it? 

I need your help.

![20180128_023026](https://user-images.githubusercontent.com/21700676/35474602-f3a653d8-03d3-11e8-8704-bb569b57c1f9.png)

**Comment by JimmyMow** [comment] 2018-01-27 21:55
this is a duplicate of #236, let's take the discussion there

**Closed by JimmyMow** 2018-01-27 21:55 UTC
