### ISSUE TITLE
I'm stuck on this loading screen

### ISSUE THREAD

**Issue by snakedye** [LN-Zap/zap-desktop#3334] opened 2020-01-28 13:10 UTC
<img width="960" alt="zap" src="https://user-images.githubusercontent.com/49378990/73266660-2c23ec00-418c-11ea-908a-6fc354f4606c.PNG">

I've waited until it reached 100% and sent Bitcoin to this address and another one on the same wallet. I don't how to get past this.

**Comment by bolatovumar** [comment] 2020-01-28 15:13
@snakedye have you tried restarting the wallet?

**Comment by snakedye** [comment] 2020-01-28 15:18
Countless times. I uninstalled the app and installed it again same result, tried recovering the wallet same thing. With autopilot, without autopilot, nothing works.

**Comment by snakedye** [comment] 2020-01-28 15:30
I use the latest.

**Comment by bolatovumar** [comment] 2020-01-28 18:31
@snakedye how long have you waited for before restarting the wallet? Try leaving it for some longer amount of time. It may just be stuck on something temporarily.

**Comment by snakedye** [comment] 2020-01-29 00:08
I've waited 5 hours and it still doesn't work.
At this point I only want my coins back

**Comment by bolatovumar** [comment] 2020-01-29 05:11
@snakedye something must be wrong here. @mrfelton @JimmyMow any idea what could be wrong here? Does Zap dump logs somewhere so we can debug this issue?

**Comment by snakedye** [comment] 2020-01-29 18:31
@JimmyMow I need some support your wallet doesn't work

**Comment by JimmyMow** [comment] 2020-01-29 20:03
@snakedye it's hard for me to understand your issue because my wallets are working fine and I can't reproduce your problem.

Yes, we have logs we can inspect. For Mac, they are at 
```
/Users/jackmallers/Library/Application Support/Zap/lnd/bitcoin/mainnet/wallet-2/logs
```

What OS are you using?

Feel free to join our Slack and DM me your logs and I can take a look

**Comment by mrfelton** [comment] 2020-01-29 20:28
I just did a test and was able to sync a fresh mainnet wallet using Zap 0.6.2.

I also checked the two BTCD nodes that service this version of the app and they are up and running and functioning normally.

> With autopilot, without autopilot

@snakedye how were you recovering the wallet with autopilot enabled? The 0.6.2 release doesn't give this option.

**Comment by snakedye** [comment] 2020-01-29 22:00
> @snakedye it's hard for me to understand your issue because my wallets are working fine and I can't reproduce your problem.
> 
> Yes, we have logs we can inspect. For example, on my Mac, they are at
> 
> ```
> /Users/jackmallers/Library/Application Support/Zap/lnd/bitcoin/mainnet/wallet-2/logs
> ```
> 
> What OS are you using?
> 
> Feel free to join our Slack and DM me your logs and I can take a look

**Comment by snakedye** [comment] 2020-01-29 22:01
@JimmyMow  
File location:
C:\Users\ndjeu\AppData\Local\Temp\zap-tmp-wallet03nNzx\logs\bitcoin\mainnet
OS: Windows 10
[lnd.log](https://github.com/LN-Zap/zap-desktop/files/4130906/lnd.log)

**Comment by tchwpkgorg** [comment] 2020-05-08 07:25
I see this also happening. Using Linux wallet, version 0.6.2-beta.

Very often after starting Zap, it is stuck on the loading screen, showing it synced 100% blocks. Sometimes it transitions to 99% for a few seconds, then again to 100%. It can be stuck on this screen for hours.

A workaround is then to press ESC, and enter the wallet again. Then it usually, but not always, open the wallet relatively fast, below 5 minutes.

**Comment by mrfelton** [comment] 2020-10-04 15:09
I'm going to close this issue since it relates to an older version of zap and syncing appears to be working fine now as far as I can see. Most likely thing is that out btcd nodes were down at the time, which can cause the sync process to stall.

**Closed by mrfelton** 2020-10-04 15:09 UTC
Labels: type: bug 🐛
