### ISSUE TITLE
Show more details in error message for channel opening failure

### ISSUE THREAD

**Issue by SteliosRammos** [LN-Zap/zap-desktop#3294] opened 2020-01-05 20:37 UTC
When I tried opening a channel with Bitrefill I got an error in the Zap wallet stating "received funding error" without much more details.

Using the lncli openchannel command I got the additional error: "err=chan size of 0.0015 BTC is below min chan size of 0.01 BTC". 

It would be nice to get that message in the Zap wallet UI. 

Also, would it be possible to make a check before attempting to open the channel, when you verify whether the pub key exists, also check whether there is a minimum channel balance required?

**Comment by bolatovumar** [comment] 2020-01-06 15:29
Weird, I remember seeing this exact error reported by Zap when trying to open a channel too small. Maybe this is a regression in a new version of Zap. What version are you using @SteliosRammos?

**Comment by SteliosRammos** [comment] 2020-01-07 23:03
Hey @bolatovumar, I believe I am running version 0.5.2-beta but I am not quite sure where to verify that. It doesn't show anywhere on the app.

**Comment by bolatovumar** [comment] 2020-01-08 03:18
@SteliosRammos the latest version is 0.6.2. To check the version go to **Zap** -> **About Zap** (this is for Mac, see screenshot below).

![Screen Shot 2020-01-07 at 7 15 23 PM](https://user-images.githubusercontent.com/1934678/71947568-26854880-3182-11ea-9ed2-9b5dd2d0ddb6.png)

On Windows you can go to **Help** -> **About Zap**.

**Comment by SteliosRammos** [comment] 2020-01-08 12:00
Thanks! I just checked and I'm actually on the 0.6.2-beta. I will leave it as a feature request for now.

**Comment by bolatovumar** [comment] 2020-01-10 04:41
@SteliosRammos interestingly enough I get this error when I try to open a channel that's too small:
![Screen Shot 2020-01-09 at 8 35 32 PM](https://user-images.githubusercontent.com/1934678/72126240-43578280-3320-11ea-96bc-6024b541d710.png)

The error comes straight from LND and Zap just passes it along and displays it to the user.

**Comment by bolatovumar** [comment] 2020-01-10 04:55
Also, it looks like there is no way to know what the minimum amount for a channel is before actually trying to open the said channel so I don't think we can prevent someone from trying to open a channel too small. Please correct me if I'm wrong @mrfelton.

**Comment by SteliosRammos** [comment] 2020-01-11 00:03
Maybe it was an isolated behaviour. Unfortunately, I didn't capture any screenshot when it happened. As for the other comment, I am curious to know wether that is indeed a protocol limitation.

**Comment by SteliosRammos** [comment] 2020-01-12 13:39
With what amount did you try opening a channel to produce that error @bolatovumar ? LND sets the minimum to 20000 sats by default. I recreated your error with an amount lower than 20000 sats, but my error was with an amount larger than the default but smaller than what was required by the other node.

**Comment by bolatovumar** [comment] 2020-01-12 17:32
@SteliosRammos i don't remember but it was something really small

**Comment by mrfelton** [comment] 2020-05-10 14:14
In master, if you open a channel that's over 20000 but under the min chan size set by the other node you will get an error like:

> received funding error from 030c3f19d742ca294a55c00376b3b355c3c90d61c6b6b39554dbc7ac19b141c14f: chan_id=811e01efcb46f319364f496f228c0d55fddf0e40536f81c681a8ef18da97ab5b, err=chan size of 0.00020001 BTC is below min chan size of 0.01 BTC

So I'm going to close this as I don't believe this reproduces any longer

**Closed by mrfelton** 2020-05-10 14:14 UTC
Labels: type: enhancement
