### ISSUE TITLE
Closing channel view doesn't show closing transaction

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1691] opened 2019-03-03 01:24 UTC
I force closed a channel and checked the closing channel for details but couldn't find the closing transaction that was broadcasted. I think users should be able to view the closing transaction and the time lock applied to their funds.

<img width="902" alt="screen shot 2019-03-03 at 9 21 51 am" src="https://user-images.githubusercontent.com/4040039/53689688-2106e700-3d96-11e9-8be2-57ddb6c6c5e5.png">

**Comment by mrfelton** [comment] 2019-03-03 07:35
I also created an issue for this yesterday! Closing as a duplicate of https://github.com/LN-Zap/zap-desktop/issues/1687

**Closed by mrfelton** 2019-03-03 07:35 UTC
Labels: duplicate
