### ISSUE TITLE
Error: A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by TomasHo** [LN-Zap/zap-desktop#236] opened 2018-01-27 18:38 UTC
Uncaught Exception:
Error: Connect Failed
    at ClientReadableStream._emitStatusIfDone (/Applications/Zap.app/Contents/Resources/app.asar/node_modules/grpc/src/client.js:255:19)
    at ClientReadableStream._readsDone (/Applications/Zap.app/Contents/Resources/app.asar/node_modules/grpc/src/client.js:221:8)
    at readCallback (/Applications/Zap.app/Contents/Resources/app.asar/node_modules/grpc/src/client.js:283:12)

**Comment by TomasHo** [comment] 2018-01-27 18:39
Happy to provide more info if needed.

**Comment by 1hiro** [comment] 2018-01-27 21:28
I get this javascript error on startup.  

Uncaught Exception:
Error: Endpoint read failed
    at ClientReadableStream._emitStatusIfDone (/Applications/Zap.app/Contents/Resources/app.asar/node_modules/grpc/src/client.js:255:19)
    at ClientReadableStream._receiveStatus (/Applications/Zap.app/Contents/Resources/app.asar/node_modules/grpc/src/client.js:233:8)
    at /Applications/Zap.app/Contents/Resources/app.asar/node_modules/grpc/src/client.js:705:12

**Comment by JimmyMow** [comment] 2018-01-28 00:58
@1hiro @TomasHo this is a duplicate of #234 

let's take this discussion over there. I gave a potential hack-fix for the time being

**Closed by JimmyMow** 2018-01-28 00:58 UTC
