### ISSUE TITLE
Pending Open Channel - Stuck for Months

### ISSUE THREAD

**Issue by squatz1** [LN-Zap/zap-desktop#3200] opened 2019-11-19 03:24 UTC
HERE IS MY ORIGINAL TICKET - THIS IS THE SAME PROBLEM FROM JUL 22 (https://github.com/LN-Zap/zap-desktop/issues/2591)

So I had had my Zap-Desktop on AutoPilot, and due to this it has opened some channels. One of them had been pending, and it is still pending for weeks. I'm unable to close / force close it as it is still open.

Also -- The TX that it has provided to show that it's opening can't be found, which is why this is still stuck.

Channel should open and then allow me to close it.

Actual Behavior
Possible Fix
Steps to Reproduce
Context
I'm trying to withdraw my funds, though I'm stuck on pending.

Your Environment
Zap version: Newest verison
Operating System and version: Windows 10

**Comment by squatz1** [comment] 2019-11-19 03:27
Here's the picture btw - https://imgur.com/a/vgeo7D9

**Comment by squatz1** [comment] 2019-12-15 17:46
I'd like to bump this, please do help.

**Comment by mrfelton** [comment] 2020-03-05 07:15
Closing as a duplicate of https://github.com/LN-Zap/zap-desktop/issues/2695

This is a bug with lnd

**Closed by mrfelton** 2020-03-05 07:15 UTC

**Comment by grubeli** [comment] 2021-03-29 23:32
DONE.
Okay. I found a way to return our funds.
if your funds are stuck like mine, I mean you send them from Zap (on-chain) wallet to Zap Lightening and is stuck on Pending.
What you need is to copy your recovery words, download new app on a different PC and recover (!) your wallet from the seed numbers you copied before. if you don't have a different PC you can use virtualization software like virtualbox (https://www.virtualbox.org) to create a virtual PC and install Zap on it.

After that, when you open your Zap on that new PC you will see all your coins on On-Chain, it means you can send it back to your original account/address or any other address
