### ISSUE TITLE
Javascript Error - Uncaught Exception: Endpoint read failed.png

### ISSUE THREAD

**Issue by CryptoChronicus** [LN-Zap/zap-desktop#277] opened 2018-02-02 00:13 UTC
just installed new release v0.1.1 beta and got this on first startup
![javascript error - uncaught exception- endpoint read failed](https://user-images.githubusercontent.com/34789878/35710173-a6952aaa-077b-11e8-98db-1fff1445d132.png)

**Comment by CryptoChronicus** [comment] 2018-02-02 00:19
channels are all gone now, and cant connect
![screenshot_1](https://user-images.githubusercontent.com/34789878/35710339-7be99bc8-077c-11e8-83b7-f9a7b9732604.png)

**Comment by jtayrone** [comment] 2018-02-02 16:49
I believe this is related to LND if you have it installed on your computer. To troubleshoot remove LND or run first then run ZAP. My suggestion is to remove the LND files in `C:\Users\username\AppData\Local\Lnd` then I tried to install ZAP.

**Comment by silver-moose** [comment] 2018-02-02 19:45
Have the same issue after I installed release 1.1 beta. Everything was working very well before with release 1.0

**Comment by JimmyMow** [comment] 2018-02-06 16:44
This suggests that that `grpc` wasn't successful in connecting to an existing LND instance. I would shut down all LND instances and give your comp a few minutes before restarting Zap for the time being

**Comment by mrfelton** [comment] 2018-07-11 23:02
Closing as a duplicate of https://github.com/LN-Zap/zap-desktop/issues/234

**Closed by mrfelton** 2018-07-11 23:02 UTC
Labels: bug, duplicate
