### ISSUE TITLE
UI bug: Fix visual cutoffs in pay/request view

### ISSUE THREAD

**Issue by thinkjanis** [LN-Zap/zap-desktop#143] opened 2017-12-29 14:30 UTC
![screenshot from 2017-12-27 18 43 34](https://user-images.githubusercontent.com/31632325/34439284-689ca2a4-ecb5-11e7-9762-4b4124159a19.png)

**Comment by pajasevi** [comment] 2017-12-30 18:18
@thinkjanis  I'm not able to reproduce that. Can you describe how that happens?

**Comment by thinkjanis** [comment] 2018-01-05 17:57
When typing 000... instead of 0.00... and leaving out the dot. With . and e. Happens almost randomly.

**Comment by mkehlmann** [comment] 2018-01-10 05:06
This issue may be tied to your screen width.  I see "00" get cutoff at any width below 1250 pixels or so.

I started to play around with how the width was set, but noticed issue #131, which would make the application window re-sizable.  Seems like it might be best to fix this width stuff after that change (if its going to be implemented), since that change may cause some global styling updates where widths are concerned.

@JimmyMow have you looked at the re-sizable stuff yet?  I might give it a go if not.

**Comment by FrimJo** [comment] 2018-01-10 12:33
I have a fix for dynamically set with of input field.

No cutoffs, it uses a ghost mechanism where the value written in the input field is placed in a hidden span-tag, and the width of the span is used to determine the with of the input field.

<img width="285" alt="skarmavbild 2018-01-10 kl 13 30 12" src="https://user-images.githubusercontent.com/4533443/34772993-69cd2352-f60a-11e7-909b-c40cadc56abe.png">
<img width="462" alt="skarmavbild 2018-01-10 kl 13 31 02" src="https://user-images.githubusercontent.com/4533443/34773049-924faf7a-f60a-11e7-9037-fd8eb39d37fd.png">
<img width="328" alt="skarmavbild 2018-01-10 kl 13 30 33" src="https://user-images.githubusercontent.com/4533443/34773009-76f60a3a-f60a-11e7-9c83-1220e96d0011.png">
<img width="474" alt="skarmavbild 2018-01-10 kl 13 31 10" src="https://user-images.githubusercontent.com/4533443/34773044-8da72a70-f60a-11e7-87eb-fb278bb857f7.png">

**Comment by Empact** [comment] 2018-01-11 00:43
This is because PayForm sets the sizing and width based on the length of the number, which consolidates "0." and "000" to "0". I made a partial fix here, aimed at "0.": #176 

@FrimJo your approach sounds much better. :P

**Comment by FrimJo** [comment] 2018-01-11 09:21
@Empact Nice fix! I'll try get a PR up regarding dynamically changing the size of the input field.

**Comment by JimmyMow** [comment] 2018-01-11 22:37
that would be great @FrimJo

**Comment by mrfelton** [comment] 2018-07-11 22:44
This is no longer an issue with the latest UI so closing this issue.

**Closed by mrfelton** 2018-07-11 22:44 UTC
