### ISSUE TITLE
When I close Zap and start it again, I get following Javascript error

### ISSUE THREAD

**Issue by larspohlmann** [LN-Zap/zap-desktop#247] opened 2018-01-28 12:39 UTC
Uncaught Exception:
Error: Connect Failed
    at ClientReadableStream._emitStatusIfDone (/Applications/Zap.app/Contents/Resources/app.asar/node_modules/grpc/src/client.js:255:19)
    at ClientReadableStream._readsDone (/Applications/Zap.app/Contents/Resources/app.asar/node_modules/grpc/src/client.js:221:8)
    at readCallback (/Applications/Zap.app/Contents/Resources/app.asar/node_modules/grpc/src/client.js:283:12)

--

MacOs 10.13.1

A reboot resolves the issue

**Comment by PlanBit** [comment] 2018-01-28 12:45
Same. Than restarted the pc and everything was fine.

**Comment by Pearse500** [comment] 2018-01-28 15:57
Same and good to know a restart gets it back. was uninstalling and reinstalling to get back to working.

**Comment by mrfelton** [comment] 2018-07-11 22:00
Can someone confirm if this issue is still reproducible with the latest code in the master branch?

**Comment by mrfelton** [comment] 2018-07-11 23:01
Closing this story as a duplicate of https://github.com/LN-Zap/zap-desktop/issues/234

**Closed by mrfelton** 2018-07-11 23:01 UTC
Labels: bug
