### ISSUE TITLE
Lost Funds after Deleting Wallet

### ISSUE THREAD

**Issue by RodsnCones** [LN-Zap/zap-desktop#1600] opened 2019-02-19 00:26 UTC
## Description
 I didn't reconnect my wallet back to the network before the deadline. I decided deleting the wallet and making a new one would be the quickest fix. It appears that I've lost access to the Bitcoin I used to fund the node for the original wallet.

I decided deleting the wallet and making a new one would be the quickest fix. It appears that I've lost access to the Bitcoin I used to fund the node. I didn't think that would happen or else I wouldn't have deleted the wallet.
## Expected Behavior
 There should be a way to recover the funds. It should not be so easy to delete a wallet if the funds are lost with it. There should be a prompt if you have funds in the wallet to prevent people from losing funds.

## Actual Behavior
 If you miss connection deadline and when you try to launch the wallet but you either get errors or can't connect. If someone sees they can delete the wallet they might just think they can delete it and start over with the same funds but the funds disappear.

## Possible Fix
Make a prompt before deleting the wallet to prevent people from losing access to their funds.

## Steps to Reproduce

- 1.
- 2.
- 3.
- 4.

## Context
 I have lost Bitcoin and can't fund my Lightning Node due to a few clicks of a button.

## Your Environment
I'm at home

- Zap Desktop version: 0.3.4
- Operating System and version: Windows 10

**Comment by JimmyMow** [comment] 2019-02-19 01:55
@RodsnCones you can't lose real BTC with Zap because our light client mode only supports testnet currently. Have you lost testnet BTC or mainnet BTC?

Also, there is a way to recover on-chain funds, you are given a 24 word seed when creating a wallet.

How are you using Zap? Are you connecting to a remote LND node or using Zap as a light client on testnet?

**Comment by RandyMcMillan** [comment] 2019-02-19 10:23
I will add something to the FAQ page about wallet recovery with the seed phrases.

**Comment by mrfelton** [comment] 2019-03-05 08:08
I'm going to close this issue since - whist sub-optimal - things are working as designed.

On-chain funds can be restored with the seed, but to restore funds from your channels you need to have backed up and recover the channel data.

Improvements to this are being worked on, such as through the work being done on static channel back ups in https://github.com/lightningnetwork/lnd/pull/2313

We have already implemented a warning that requires the user to both check a checkbox to confirm that they understand that their wallet data will be deleted, as well as confirming the delete action itself before we delete wallet data.

**Closed by mrfelton** 2019-03-05 08:08 UTC
