### ISSUE TITLE
unable to find a path to destination

### ISSUE THREAD

**Issue by curiosity81** [LN-Zap/zap-desktop#261] opened 2018-01-29 17:24 UTC
Hi,

I am playing around with Zap. However, I cannot make any payment. I always get the "unable to find a path to destination" error even though I am directly connected to a Y'alls node.

Moreover, the GUI (Linux) always keeps the input. That is, e.g., if one has copied an URI into some field, reopening the window with the field keeps the URI. So one always has to remove the string in the field.  There should be a "clear" -button or similar.

Also closing the wallet does not stop the porgram. If it was started in a terminal via "./", one hast to use Ctrl+C to kill it, otherwise the terminal blocks.

Regards,
cu

**Comment by CryptoChronicus** [comment] 2018-01-29 23:05
I am also unable to find a path to the destination, even though I copied the Peer Info and am connected to the same Node apparently
![unable to find a path to destination](https://user-images.githubusercontent.com/34789878/35539284-915239e2-0516-11e8-8a52-f2cbf7420be4.png)

**Comment by coever99** [comment] 2018-01-30 16:39
Same problem with Yalls even though I am connected directly to Yalls. However, I have no problems sending payment to or receiving from htlc.me. This is strange since the connection to Yalls is my only connection.

**Comment by curiosity81** [comment] 2018-01-30 17:33
It is still not working. I connected to

031dc566ea7e71531edba5929e11de824bf4bfd2062f840499223398a56644e5e2@52.3.235.238

today. But still no path to destination.

However, it worked at the beginning, two days ago.

**Comment by CryptoChronicus** [comment] 2018-01-30 21:24
## Thus far, for me, it says "Unable to find a path to destination" every single time. I have never successfully sent a LN payment on testnet.

also, about this:
"Moreover, the GUI (Linux) always keeps the input. That is, e.g., if one has copied an URI into some field, reopening the window with the field keeps the URI. So one always has to remove the string in the field. There should be a "clear" -button or similar."

I also experience this problem. It should either automatically clear at some point, or at least a button to clear. Ideally, a button and a checkbox to either leave it on auto-clear, or manually clear in case your flow is better like that. Some people prefer the flow of actually manually clicking.

**Comment by CryptoChronicus** [comment] 2018-02-01 00:12
Try it now. Got it working for me :)
![screenshot_7](https://user-images.githubusercontent.com/34789878/35654340-3d950134-06b2-11e8-9aa8-a9e379f15896.png)

**Comment by JimmyMow** [comment] 2018-02-01 17:55
This is a normal error. Just means your node is unable to find a route. The UX/error handling can be better but this is not a bug. Closing

**Closed by JimmyMow** 2018-02-01 17:55 UTC

**Comment by rhinoted** [comment] 2018-02-02 21:14
I have the same problem: Channel opened with yalls but when I pay I get "unable to find a path to destination".

I succeeded making this just the firs day of testing.. then not anymore..

**Comment by iaron** [comment] 2018-02-03 04:56
I'm also getting this error when trying to pay to read an Yalls article. I read that this was a temporary network error, but and I've been trying this for a couple days and never worked for me.

Windows 8.1 Pro

![image](https://user-images.githubusercontent.com/4040172/35763167-177f55bc-088d-11e8-8620-001181088987.png)
--
![image](https://user-images.githubusercontent.com/4040172/35763171-23bebec6-088d-11e8-83d3-ee262031b86e.png)

**Comment by 52edc** [comment] 2018-02-26 21:37
Same problem. Many channels opened but "unable to find a path to destination".

**Comment by Crypto2** [comment] 2019-05-18 13:40
Same problem here, I have a channel opened directly with the destination node and I even closed all my other channels so this is the only one left open.
