### ISSUE TITLE
Lnd has unexpectedly quit! Error code: 1   From a cellular connection

### ISSUE THREAD

**Issue by nycnikato** [LN-Zap/zap-desktop#2112] opened 2019-04-25 00:43 UTC
I had been having some issues connecting to my wallet where the balance and BTC transactions were not showing. I had a suspicion that my network environment had something to do with it. I am using T-Mobile 4g internet via the hotspot function of my cell phone. I took my laptop to my workplace wifi and was able to have the wallet working completely and fully synced with no issues . I then put the laptop back on T-mobile hotspot and now I am experiencing the issue. Lnd has unexpectedly quit! Error code: 1 - I suspect that T-mobile may have some kind of VPN or an exotic network setup that is preventing LND from starting and that LND may require unencumbered access to the github site. I also tried using a VPN to see if that would resolve, but no luck.
To reproduce:
Try using T-mobile internet connection as a hotspot to laptop
Run Zap Client
Enter your password if any
wait for the message that the network is synced (Visa who..)
Wait about another 20 seconds and the error will come.

I am using Arch Linux

At the very least a VPN should be able to resolve the issue. I am using PIA VPN in hopes of resolving but this did not resolve.

The ideal behavior would be that LND would connect from behind a cellular connection and at the very least through a VPN behind such a connection. Any resolution should make access a lot more resilient under unusual network conditions such as Wifi Hotspot, hostile regime firewall, workplace firewall, blocked ports, etc.

my /etc/hosts file is OK

This is NOT a showstopper as very few people I think would be using ZAP under such network conditions. Freedom of commerce will certainly require that such situations be accounted for.
Zap .4.1-beta
Antergos 19.04
T-mobile

**Comment by nycnikato** [comment] 2019-04-25 01:17
I had been having some issues connecting to my wallet where the balance and BTC transactions were not showing. I had a suspicion that my network environment had something to do with it. I am using T-Mobile 4g internet via the hotspot function of my cell phone. I took my laptop to my workplace wifi and was able to have the wallet working completely and fully synced with no issues . I then put the laptop back on T-mobile hotspot and now I am experiencing the issue. Lnd has unexpectedly quit! Error code: 1  - I suspect that T-mobile may have some kind of VPN or an exotic network setup that is preventing LND from starting and that LND may require unencumbered access to the github site. I also tried using a VPN to see if that would resolve, but no luck.
To reproduce: 
Try using T-mobile internet connection  as a hotspot to laptop 
Run Zap Client
Enter your password if any
wait for the message that the network is synced (Visa who..)
Wait about another 20 seconds and the error will come. 

I am using Arch Linux

At the very least a VPN should be able to resolve the issue. I am using PIA VPN in hopes of resolving but this did not resolve.

The ideal behavior would be that LND would connect from behind a cellular connection and at the very least through a VPN behind such a connection. Any resolution should make access a lot more resilient under unusual network conditions such as Wifi Hotspot, hostile regime firewall, workplace firewall, blocked ports, etc. 

my /etc/hosts file is OK

This is NOT a showstopper as very few people I think would be using ZAP under such network conditions. Freedom of commerce will certainly require that such situations be accounted for.

**Comment by mrfelton** [comment] 2019-07-13 18:41
Hi,

The `lnd unexpectedly quit` can happen if lnd crashes. I can't really say specifically why that might have been happening in your case, however the bug was reported against Zap 0.4.x which ran an older and more unstable version of lnd. The currently (0.5.x) version of Zap uses a more recent lnd version.

I'm going to close this issue as we are not able to reproduce the problem and it's quite likely that whatever was causing it has been resolved in the more recent lnd versions.

Please feel free to reopen if this is still an issue for you with Zap 0.5.x. Thanks!

**Closed by mrfelton** 2019-07-13 18:41 UTC
