### ISSUE TITLE
Connecting v0.2.2-beta to LND-0.5-beta node crashes LND Node...

### ISSUE THREAD

**Issue by AmazingDroopy** [LN-Zap/zap-desktop#839] opened 2018-10-04 19:33 UTC
When connecting ZAP desktop to running LND Node, LND crashes.

Log:
Oct 04 21:22:53 RBP1 lnd[17351]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 04 21:22:53 RBP1 lnd[17351]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x78c4e8]
Oct 04 21:22:53 RBP1 lnd[17351]: goroutine 85981 [running]:
Oct 04 21:22:53 RBP1 lnd[17351]: main.(*rpcServer).GetTransactions(0x34ac380, 0xbf41a0, 0x5f118a0, 0x1314240, 0x34ac380, 0x0, 0x31b4204)
Oct 04 21:22:53 RBP1 lnd[17351]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/rpcserver.go:3021 +0x1fc
Oct 04 21:22:53 RBP1 lnd[17351]: github.com/lightningnetwork/lnd/lnrpc._Lightning_GetTransactions_Handler.func1(0xbf41a0, 0x5f118a0, 0x8fc3a0, 0x1314240, 0x1, 0x1, 0x0, 0x0)
Oct 04 21:22:53 RBP1 lnd[17351]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:6271 +0x68
Oct 04 21:22:53 RBP1 lnd[17351]: github.com/lightningnetwork/lnd/macaroons.(*Service).UnaryServerInterceptor.func1(0xbf41a0, 0x5f118a0, 0x8fc3a0, 0x1314240, 0x32e38f0, 0x32e3900, 0x73dea6c, 0x5c0be4, 0x30, 0x91ab50)
Oct 04 21:22:53 RBP1 lnd[17351]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/macaroons/service.go:126 +0x108
Oct 04 21:22:53 RBP1 lnd[17351]: github.com/lightningnetwork/lnd/lnrpc._Lightning_GetTransactions_Handler(0x970730, 0x34ac380, 0xbf41a0, 0x5f118a0, 0x4cb2ba0, 0x34d7d40, 0x0, 0x0, 0x4, 0x38f7032)
Oct 04 21:22:53 RBP1 lnd[17351]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:6273 +0x118
Oct 04 21:22:53 RBP1 systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 04 21:22:53 RBP1 systemd[1]: lnd.service: Unit entered failed state.
Oct 04 21:22:53 RBP1 systemd[1]: lnd.service: Failed with result 'exit-code'.

Using ZAP v0.2.1-beta to connect to LND v0.4.2-beta did not crash the LN Node.
Without connecting ZAP Desktop ...LND Node runs fine.

- Zap Desktop version: v0.2.2-beta
- Bitcoin Core Daemon version v0.16.3
- LND version 0.5.0-beta commit=3b2c807288b1b7f40d609533c1e96a510ac5fa6d
- Operating System and version: Raspbian GNU/Linux 9.4 (stretch)

**Comment by AmazingDroopy** [comment] 2018-10-04 19:35
ZAP Desktop running on MACOS 10.12.6

**Comment by mrfelton** [comment] 2018-10-05 06:47
@AmazingDroopy I would suggest that you update your LND node if possible. 0.4.2-beta has many problems and will crash with runtime panics like this in many different scenarios.

**Comment by mrfelton** [comment] 2018-11-05 22:09
@AmazingDroopy this would be an issue with lnd rather than with Zap. Do you know if this is still an issue with the latest lnd master branch? Are you able to reliably reproduce the issue? If so, I would suggest that you raise it with the lnd team.

**Comment by gcomte** [comment] 2018-11-29 23:52
@AmazingDroopy I had the same issue. Zap 0.2.2 with LND 0.5.0 .
**Updating to LND 0.5.1-beta fixes this issue.**

**Comment by AmazingDroopy** [comment] 2018-11-30 11:30
Great, I will do exactly that and try again. Thanks for sharing.

Richard.

**Comment by mrfelton** [comment] 2018-12-01 10:47
Thanks for the update guys. I'm, going to close this since it looks to be fixed upstream with the latest lnd release - and in any case, this would be something that is out of our control since the problem was with lnd rather than zap specifically.

**Closed by mrfelton** 2018-12-01 10:47 UTC
Labels: bug
