### ISSUE TITLE
ZapDesktop.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by pieman64** [LN-Zap/zap-desktop#2428] opened 2019-06-14 10:30 UTC
Error as per bug report title.

## Description

Not used Zap desktop for many months as I have been waiting for Android version. When I open Zap desktop it tells me to click for upgrade. When Zap restarts I get:

"The procedure entry point av_register_all could not be located in the dynamic link library. C:\Users\...\AppData\Local\Programs\zap-desktop\ZapDesktop.exe

## Expected Behavior

I expect Zap desktop to open on request

## Actual Behavior

Zap crashes with error above

## Possible Fix

No idea

## Steps to Reproduce

Try to upgrade from an old Zap version to a new one

## Context

Trying to use Zap

## Your Environment

- Zap version: Installed 23 Dec 2018 but can't see version as system crashes.
- Operating System and version: Windows 8.1

**Comment by JimmyMow** [comment] 2019-07-11 18:21
@pieman64 Can you try the new Zap Desktop 0.5.0 release? Maybe this fixes your issue? We haven't been able to reproduce this.

https://github.com/LN-Zap/zap-desktop/releases

**Comment by mrfelton** [comment] 2019-07-30 13:03
I'm going to close this issue as we are unable to reproduce the issue and it hasn't been updated by OP in over 6 weeks.

Please feel free to reopen if the problem persists for you after updating Zap to the latest version.

**Closed by mrfelton** 2019-07-30 13:03 UTC
Labels: needs feedback, scope: windows, type: bug 🐛
