### ISSUE TITLE
Multiple wallets are selected in wallets menu

### ISSUE THREAD

**Issue by korhaliv** [LN-Zap/zap-desktop#2351] opened 2019-06-05 10:35 UTC
## Description
Multiple wallets are highlighted in wallets menu in `next`
![image](https://user-images.githubusercontent.com/14069193/58950149-bb603780-8796-11e9-9666-d807d5d058c7.png)

**Comment by mrfelton** [comment] 2019-06-13 08:33
This has not been reproducible for some time and the menus have since been overhauled, so closing for now.

**Closed by mrfelton** 2019-06-13 08:33 UTC
Labels: type: bug 🐛
