### ISSUE TITLE
"unable to connect to host" potential TLD issue

### ISSUE THREAD

**Issue by jlopp** [LN-Zap/zap-desktop#860] opened 2018-10-18 21:36 UTC
## Description
We have a BTCPay server that has been running for a month or so and now we wish to enable lightning payments via the locally running dockerized lnd instance. I've successfully gotten the btcpay server itself to connect to lnd, but when attempting to connect via Zap it returns an odd error.

the connection string config contains:
"host": "btcpay.keys.casa",

## Expected Behavior

Zap should connect to the node

## Actual Behavior

Zap returns an error:
`Unable to connect to host: 2 UNKNOWN:`

When I try to connect to other domains such as a .net TLD it gives a very different error, which is why I suspect the TLD as the culprit. 

## Possible Fix

Maybe there's an issue with the networking library and the TLDs to which it supports connecting?

## Steps to Reproduce

Attempt to connect to an lnd instance on a .casa TLD

## Context

Establishing a connection to lnd

## Your Environment

Zap Desktop v0.2.2beta on PureOS 8.0
LND 0.5 on AWS EC2

**Comment by jlopp** [comment] 2018-12-05 16:38
Hmmm this is tricky because btcpay is managing lnd via docker. It looks like notls=1 is set in the lnd config. I don't see tlsextradomain being set.

**Comment by mrfelton** [comment] 2018-12-05 17:05
@jlopp Thinking about this some more, I think `tlsextradomain` is only used in conjunction with lnd's self generated certs which BTCPay is not using. BTC Pay is using it's own TLS cert which I think would be valid for your domain. At least, inspecting the cert at https://btcpay.keys.casa/ shows that it is valid.

@NicolasDorier - any thoughts what might be the issue?

I'll spin up a BTCPay server and see if I can reproduce.

**Comment by jlopp** [comment] 2018-12-07 22:15
Hm that may have been it; I got a few errors while running those commands.

```sh
root@btcpay:~# docker exec btcpayserver_lnd_bitcoin rm /data/admin.macaroon
root@btcpay:~# docker exec btcpayserver_lnd_bitcoin rm /data/invoice.macaroon
rm: can't remove '/data/invoice.macaroon': No such file or directory
root@btcpay:~# docker exec btcpayserver_lnd_bitcoin rm /data/readonly.macaroon
rm: can't remove '/data/readonly.macaroon': No such file or directory
root@btcpay:~# docker exec btcpayserver_lnd_bitcoin rm /data/data/macaroons.db
rm: can't remove '/data/data/macaroons.db': No such file or directory
root@btcpay:~# docker exec btcpayserver_lnd_bitcoin rm /data/data/chain/bitcoin/mainnet/invoice.macaroon
root@btcpay:~# docker exec btcpayserver_lnd_bitcoin rm /data/data/chain/bitcoin/mainnet/macaroons.db
root@btcpay:~# docker exec btcpayserver_lnd_bitcoin rm /data/data/chain/bitcoin/mainnet/readonly.macaroon
root@btcpay:~# docker restart btcpayserver_lnd_bitcoin
btcpayserver_lnd_bitcoin
```

Though we moved the server to a new environment since I opened this ticket; now I'm getting a "Failed to connect before the deadline" error. Perhaps it's a firewall issue... but this talks over port 443, right? and our btcpay web site loads just fine...

**Comment by NicolasDorier** [comment] 2018-12-08 14:36
Yeah the error are ok.

NGINX listen incoming requests, and forward it directly to LND. So if you host LND via the docker deploy, it should be properly setup.

You can give a look to lnd logs with `docker logs btcpayserver_lnd_bitcoin`. if you see anything strange.
Also can you create LN invoice properly via BTCPay?

**Comment by jlopp** [comment] 2018-12-13 16:54
I'm still getting the "Unable to connect to host: Failed to connect before the deadline" error in zap. Not seeing any errors in the btcpay lnd docker logs. We are able to create invoices just fine - our btcpay store has been processing both on-chain and lightning payments just fine.

Is it normal for the connection json to have "restrictedMacaroon": null ?

**Comment by mrfelton** [comment] 2018-12-13 17:03
@jlopp if you start up Zap from the command line you can enable some debug output that might help you diagnose the issue.

`DEBUG_LEVEL=debug DEBUG=zap* /path/to/zap`

`Failed to connect before the deadline` usually indicates that you are connecting to the wrong port, firewall has the port blocked, or you are using an ssl cert that doesn't match what you are trying to connect to.

**Comment by jlopp** [comment] 2018-12-13 17:16
```
 zap:main [DBG]  [FSM] onBeforeConnectLnd... +2ms
  zap:main [INF]  Connecting to custom lnd instance +0ms
  zap:main [INF]   > host: btcpay.keys.casa:443 +0ms
  zap:main [INF]   > cert: undefined +0ms
  zap:main [INF]   > macaroon: <redacted> +1ms
  zap:main [INF]  Establishing connection to Lightning gRPC interface... +1ms
  zap:main [INF]  Connecting to Lightning gRPC service +3ms
  zap:main [WRN]  Unable to connect to Lighitnng gRPC interface: Error: Failed to connect before the deadline at checkState (/opt/ZapDesktop/resources/app.asar/node_modules/grpc/src/client.js:720:16) +20s
  zap:main [INF]  Sending message to renderer process: { msg: 'startLndError', data: { host: 'Unable to connect to host: Failed to connect before the deadline' } } +2ms
(node:31428) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to connect before the deadline
(node:31428) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jlopp** [comment] 2018-12-13 17:18
I suspect the SSL cert may be the likely suspect because IIRC btcpay generates one automatically

**Comment by mrfelton** [comment] 2018-12-13 17:53
The SSL cert that btcpay generates *should* be already trusted by your OS. So we don't pass it along with our grpc calls.

@jlopp have you tried this from another machine? I'm wondering if it's possible that the machine that you are testing from doesn't have the relevant root certs in place.

**Comment by mrfelton** [comment] 2018-12-13 17:57
I believe that the certs generated by BTCPay uses these:

https://letsencrypt.org/certificates/

**Comment by mrfelton** [comment] 2018-12-13 17:59
Another thing that you could try, just to rule our Zap, is connecting from the same machine that is runnign Zap but using `lncli`. Something like:

`lncli --rpcserver=btcpay.keys.casa:443 --macaroonpath=/path/to/admin.macaroon getinfo`

**Comment by jlopp** [comment] 2018-12-13 18:42
It's all screwy due to lnd running in docker. Somehow even the root user doesn't see the macaroon

```
/usr/bin/bitcoin-lncli.sh --rpcserver=btcpay.keys.casa:443 --macaroonpath=/var/lib/docker/volumes/generated_lnd_bitcoin_datadir/_data/admin.macaroon getinfo
[lncli] unable to read macaroon path (check the network setting!): open /var/lib/docker/volumes/generated_lnd_bitcoin_datadir/_data/admin.macaroon: no such file or directory
```

**Comment by NicolasDorier** [comment] 2018-12-14 04:47
First time I see this problem of not finding `admin.macaroon` after you ran https://docs.btcpayserver.org/faq-and-common-issues/faq-lightningnetwork#lnd-connection-issues-after-an-update

What do you see in the `/var/lib/docker/volumes/generated_lnd_bitcoin_datadir/_data` folder?

**Comment by NicolasDorier** [comment] 2018-12-14 04:48
```
/usr/bin/bitcoin-lncli.sh --rpcserver=btcpay.keys.casa:443 --macaroonpath=/var/lib/docker/volumes/generated_lnd_bitcoin_datadir/_data/admin.macaroon getinfo
```

Can't possibly work. Because the macaroon is fetch from inside the docker container who does not have access to `/var/lib/docker/volumes/generated_lnd_bitcoin_datadir/_data`.

**Comment by mrfelton** [comment] 2018-12-28 18:35
@jlopp can you confirm if this is still an issue for you in 0.3.2 please?

Were you able to connect to the instance using `lncli`?

Thanks!

**Comment by jlopp** [comment] 2019-02-14 13:27
It was failing in 3.2 and now again in 3.4, though the error keeps changing with each version. Here's the 3.4 error:

```
 zap:main [INF]  Connecting to custom lnd instance +0ms
  zap:main [INF]   > host: btcpay.keys.casa:443 +0ms
  zap:main [INF]   > cert: undefined +0ms
  zap:main [INF]   > macaroon: <REDACTED> +1ms
  zap:main [INF]  Establishing connection to Lightning gRPC interface... +0ms
  zap:main [INF]  Connecting to Lightning gRPC service +0ms
  zap:main [DBG]  Establishing gRPC connection with proto file /opt/ZapDesktop/resources/resources/proto/lnrpc/0.5.2-rc3.proto +278ms
  zap:main [WRN]  Unable to connect to Lightning gRPC interface: { Error: Internal HTTP2 error at t.Http2CallStream.Function (/opt/ZapDesktop/resources/app.asar/dist/webpack:/node_modules/@grpc/grpc-js/build/src/client.js:94:1) at t.Http2CallStream.emit (events.js:187:15) at t.Http2CallStream.[object Object] [as endCall] (/opt/ZapDesktop/resources/app.asar/dist/webpack:/node_modules/@grpc/grpc-js/build/src/call-stream.js:72:1) at ClientHttp2Stream.this (/opt/ZapDesktop/resources/app.asar/dist/webpack:/node_modules/@grpc/grpc-js/build/src/call-stream.js:305:1) at ClientHttp2Stream.emit (events.js:182:13) at emitErrorNT (internal/streams/destroy.js:82:8) at emitErrorAndCloseNT (internal/streams/destroy.js:50:3) at process._tickCallback (internal/process/next_tick.js:63:19) code: 13, details: 'Internal HTTP2 error', metadata: l { internalRepr: {} } } +583ms
  zap:main [INF]  Sending message to renderer process: { msg: 'startLndError', data: { host: 'Unable to connect to host: Internal HTTP2 error' } } +10ms
  zap:main [ERR]  Unable to start lnd: Internal HTTP2 error +0ms

```

**Comment by NicolasDorier** [comment] 2019-02-14 14:15
@jlopp recently I saw report of LND json API which stop working for some unknown reason on some instances.

A `btcpay-restart.sh` seems to fix it. I am unsure if that is the root of your problem though. It is probably not if the 3.3 was workingfine.

**Comment by jlopp** [comment] 2019-02-14 14:21
To be clear, when I'm on the machine lncli works fine. Also, our lnd node has nearly 150 peers and channels, so it also seems to be healthy. The only "weird" thing about our setup that might be causing issues is that we have btcpay behind an AWS load balancer - I've seen load balancers cause issues with other services such as OpenBazaar...

**Comment by NicolasDorier** [comment] 2019-02-17 02:53
@jlopp I tried the latest version against my BTCPay's LND and it works.

Given your error, I think it is probably the load balancer. 
Can you try 3.3 again to be sure it is not the problem?

**Comment by mrfelton** [comment] 2019-07-31 11:44
I'm going to close this issue due to lack of recent activity and the fact that it pertains to an older release of Zap. In our testing connections with BTCPayServer are working normally. Please feel free to reopen this issue of the problem persists with the most recent release.

**Closed by mrfelton** 2019-07-31 11:44 UTC
Labels: type: bug 🐛
